/* Typed native module interface. */
#ifndef G_NATIVE_PUBLIC_H
#define G_NATIVE_PUBLIC_H

#include <stdint.h>
#ifdef __cplusplus
extern "C" {
#endif
void GameImport_Printf( const char *fmt );
void GameImport_Error( const char *fmt );
int GameImport_Milliseconds( void );
int GameImport_Argc( void );
void GameImport_Argv( int n, char *buffer, int bufferLength );
int GameImport_FS_FOpenFile( const char *qpath, void *f, int mode );
void GameImport_FS_Read( void *buffer, int len, int f );
void GameImport_FS_Write( const void *buffer, int len, int f );
void GameImport_FS_FCloseFile( int f );
int GameImport_FS_GetFileList( const char *path, const char *extension, char *listbuf, int bufsize );
int GameImport_FS_Seek( int f, int64_t offset, int origin );
void GameImport_SendConsoleCommand( int exec_when, const char *text );
void GameImport_Cvar_Register( void *cvar, const char *var_name, const char *value, int flags );
void GameImport_Cvar_Update( void *cvar );
int GameImport_WriteCvarState( void *writer, const char *group, uint32_t slot, const char *name );
int GameImport_ReadCvarState( const void *reader, const char *group, uint32_t slot, const char *name, int apply, int removable );
void GameImport_Cvar_Set( const char *var_name, const char *value );
int GameImport_Cvar_VariableIntegerValue( const char *var_name );
void GameImport_Cvar_VariableStringBuffer( const char *var_name, char *buffer, int bufsize );
void GameImport_LocateGameData( void *gEnts, int numGEntities, int sizeofGEntity_t, void *clients, int sizeofGClient );
void GameImport_DropClient( int clientNum, const char *reason );
void GameImport_SendServerCommand( int clientNum, const char *text );
void GameImport_SetConfigstring( int num, const char *string );
void GameImport_GetConfigstring( int num, char *buffer, int bufferSize );
int GameImport_GetPlayerIdentity( int clientNum, uint64_t *id );
void GameImport_GetUserinfo( int num, char *buffer, int bufferSize );
void GameImport_SetUserinfo( int num, const char *buffer );
void GameImport_GetServerinfo( char *buffer, int bufferSize );
void GameImport_SetBrushModel( void *ent, const char *name );
void GameImport_Trace( void *results, const float *start, const float *mins, const float *maxs, const float *end, int passEntityNum, int contentmask );
int GameImport_SetEntityReplication( int number, int priority, float radius );
void *GameImport_AllocLevelMemory( uint32_t bytes );
void GameImport_TraceFiltered( void *results, const float *start, const float *end, int passEntityNum, int contentmask, const uint8_t *ignored );
void GameImport_TraceCapsule( void *results, const float *start, const float *mins, const float *maxs, const float *end, int passEntityNum, int contentmask );
int GameImport_PointContents( const float *point, int passEntityNum );
int GameImport_InPVS( const float *p1, const float *p2 );
int GameImport_InPVSIgnorePortals( const float *p1, const float *p2 );
void GameImport_AdjustAreaPortalState( void *ent, int open );
int GameImport_AreasConnected( int area1, int area2 );
void GameImport_LinkEntity( void *ent );
void GameImport_UnlinkEntity( void *ent );
int GameImport_EntitiesInBox( const float *mins, const float *maxs, int *list, int maxcount );
int GameImport_EntityContact( const float *mins, const float *maxs, const void *ent );
int GameImport_EntityContactCapsule( const float *mins, const float *maxs, const void *ent );
int GameImport_BotAllocateClient( void );
void GameImport_BotFreeClient( int clientNum );
void GameImport_GetUsercmd( int clientNum, void *cmd );
int GameImport_GetEntityToken( char *buffer, int bufferSize );
int GameImport_DebugPolygonCreate( int color, int numPoints, void *points );
void GameImport_DebugPolygonDelete( int id );
int GameImport_RealTime( void *qtime );
void GameImport_SnapVector( float *v );
int GameImport_BotLibSetup( void );
int GameImport_BotLibShutdown( void );
int GameImport_BotLibVarSet( char *var_name, char *value );
int GameImport_BotLibVarGet( char *var_name, char *value, int size );
int GameImport_BotLibDefine( char *string );
int GameImport_BotLibStartFrame( float time );
int GameImport_BotLibLoadMap( const char *mapname );
int GameImport_BotLibUpdateEntity( int ent, void *bue );
int GameImport_BotLibTest( int parm0, char *parm1, float *parm2, float *parm3 );
int GameImport_BotGetSnapshotEntity( int clientNum, int sequence );
int GameImport_BotGetServerCommand( int clientNum, char *message, int size );
void GameImport_BotUserCommand( int clientNum, void *ucmd );
void GameImport_AAS_EntityInfo( int entnum, void *info );
int GameImport_AAS_Initialized( void );
void GameImport_AAS_PresenceTypeBoundingBox( int presencetype, float *mins, float *maxs );
float GameImport_AAS_Time( void );
int GameImport_AAS_PointAreaNum( float *point );
int GameImport_AAS_PointReachabilityAreaIndex( float *point );
int GameImport_AAS_TraceAreas( float *start, float *end, int *areas, void *points, int maxareas );
int GameImport_AAS_BBoxAreas( float *absmins, float *absmaxs, int *areas, int maxareas );
int GameImport_AAS_AreaInfo( int areanum, void *info );
int GameImport_AAS_PointContents( float *point );
int GameImport_AAS_NextBSPEntity( int ent );
int GameImport_AAS_ValueForBSPEpairKey( int ent, char *key, char *value, int size );
int GameImport_AAS_VectorForBSPEpairKey( int ent, char *key, float *v );
int GameImport_AAS_FloatForBSPEpairKey( int ent, char *key, float *value );
int GameImport_AAS_IntForBSPEpairKey( int ent, char *key, int *value );
int GameImport_AAS_AreaReachability( int areanum );
int GameImport_AAS_AreaTravelTimeToGoalArea( int areanum, float *origin, int goalareanum, int travelflags );
int GameImport_AAS_EnableRoutingArea( int areanum, int enable );
int GameImport_AAS_PredictRoute( void *route, int areanum, float *origin, int goalareanum, int travelflags, int maxareas, int maxtime, int stopevent, int stopcontents, int stoptfl, int stopareanum );
int GameImport_AAS_AlternativeRouteGoals( float *start, int startareanum, float *goal, int goalareanum, int travelflags, void *altroutegoals, int maxaltroutegoals, int type );
int GameImport_AAS_Swimming( float *origin );
int GameImport_AAS_PredictClientMovement( void *move, int entnum, float *origin, int presencetype, int onground, float *velocity, float *cmdmove, int cmdframes, int maxframes, float frametime, int stopevent, int stopareanum, int visualize );
void GameImport_EA_Say( int client, char *str );
void GameImport_EA_SayTeam( int client, char *str );
void GameImport_EA_Command( int client, char *command );
void GameImport_EA_Action( int client, int action );
void GameImport_EA_Gesture( int client );
void GameImport_EA_Talk( int client );
void GameImport_EA_Attack( int client );
void GameImport_EA_Use( int client );
void GameImport_EA_Respawn( int client );
void GameImport_EA_Crouch( int client );
void GameImport_EA_MoveUp( int client );
void GameImport_EA_MoveDown( int client );
void GameImport_EA_MoveForward( int client );
void GameImport_EA_MoveBack( int client );
void GameImport_EA_MoveLeft( int client );
void GameImport_EA_MoveRight( int client );
void GameImport_EA_SelectWeapon( int client, int weapon );
void GameImport_EA_Jump( int client );
void GameImport_EA_DelayedJump( int client );
void GameImport_EA_Move( int client, float *dir, float speed );
void GameImport_EA_View( int client, float *viewangles );
void GameImport_EA_EndRegular( int client, float thinktime );
void GameImport_EA_GetInput( int client, float thinktime, void *input );
void GameImport_EA_ResetInput( int client );
int GameImport_BotLoadCharacter( char *charfile, float skill );
void GameImport_BotFreeCharacter( int character );
float GameImport_Characteristic_Float( int character, int index );
float GameImport_Characteristic_BFloat( int character, int index, float min, float max );
int GameImport_Characteristic_Integer( int character, int index );
int GameImport_Characteristic_BInteger( int character, int index, int min, int max );
void GameImport_Characteristic_String( int character, int index, char *buf, int size );
int GameImport_BotAllocChatState( void );
void GameImport_BotFreeChatState( int handle );
void GameImport_BotQueueConsoleMessage( int chatstate, int type, char *message );
void GameImport_BotRemoveConsoleMessage( int chatstate, int handle );
int GameImport_BotNextConsoleMessage( int chatstate, void *cm );
int GameImport_BotNumConsoleMessages( int chatstate );
void GameImport_BotInitialChat( int chatstate, char *type, int mcontext, char *var0, char *var1, char *var2, char *var3, char *var4, char *var5, char *var6, char *var7 );
int GameImport_BotNumInitialChats( int chatstate, char *type );
int GameImport_BotReplyChat( int chatstate, char *message, int mcontext, int vcontext, char *var0, char *var1, char *var2, char *var3, char *var4, char *var5, char *var6, char *var7 );
int GameImport_BotChatLength( int chatstate );
void GameImport_BotEnterChat( int chatstate, int client, int sendto );
void GameImport_BotGetChatMessage( int chatstate, char *buf, int size );
int GameImport_StringContains( char *str1, char *str2, int casesensitive );
int GameImport_BotFindMatch( char *str, void *match, uint64_t context );
void GameImport_BotMatchVariable( void *match, int variable, char *buf, int size );
void GameImport_UnifyWhiteSpaces( char *string );
void GameImport_BotReplaceSynonyms( char *string, uint64_t context );
int GameImport_BotLoadChatFile( int chatstate, char *chatfile, char *chatname );
void GameImport_BotSetChatGender( int chatstate, int gender );
void GameImport_BotSetChatName( int chatstate, char *name, int client );
void GameImport_BotResetGoalState( int goalstate );
void GameImport_BotResetAvoidGoals( int goalstate );
void GameImport_BotRemoveFromAvoidGoals( int goalstate, int number );
void GameImport_BotPushGoal( int goalstate, void *goal );
void GameImport_BotPopGoal( int goalstate );
void GameImport_BotEmptyGoalStack( int goalstate );
void GameImport_BotDumpAvoidGoals( int goalstate );
void GameImport_BotDumpGoalStack( int goalstate );
void GameImport_BotGoalName( int number, char *name, int size );
int GameImport_BotGetTopGoal( int goalstate, void *goal );
int GameImport_BotGetSecondGoal( int goalstate, void *goal );
int GameImport_BotChooseLTGItem( int goalstate, float *origin, int *inventory, int travelflags );
int GameImport_BotChooseNBGItem( int goalstate, float *origin, int *inventory, int travelflags, void *ltg, float maxtime );
int GameImport_BotTouchingGoal( float *origin, void *goal );
int GameImport_BotItemGoalInVisButNotVisible( int viewer, float *eye, float *viewangles, void *goal );
int GameImport_BotGetLevelItemGoal( int index, char *classname, void *goal );
int GameImport_BotGetNextCampSpotGoal( int num, void *goal );
int GameImport_BotGetMapLocationGoal( char *name, void *goal );
float GameImport_BotAvoidGoalTime( int goalstate, int number );
void GameImport_BotSetAvoidGoalTime( int goalstate, int number, float avoidtime );
void GameImport_BotInitLevelItems( void );
void GameImport_BotUpdateEntityItems( void );
int GameImport_BotLoadItemWeights( int goalstate, char *filename );
void GameImport_BotFreeItemWeights( int goalstate );
void GameImport_BotInterbreedGoalFuzzyLogic( int parent1, int parent2, int child );
void GameImport_BotSaveGoalFuzzyLogic( int goalstate, char *filename );
void GameImport_BotMutateGoalFuzzyLogic( int goalstate, float range );
int GameImport_BotAllocGoalState( int state );
void GameImport_BotFreeGoalState( int handle );
void GameImport_BotResetMoveState( int movestate );
void GameImport_BotAddAvoidSpot( int movestate, float *origin, float radius, int type );
void GameImport_BotMoveToGoal( void *result, int movestate, void *goal, int travelflags );
int GameImport_BotMoveInDirection( int movestate, float *dir, float speed, int type );
void GameImport_BotResetAvoidReach( int movestate );
void GameImport_BotResetLastAvoidReach( int movestate );
int GameImport_BotReachabilityArea( float *origin, int testground );
int GameImport_BotMovementViewTarget( int movestate, void *goal, int travelflags, float lookahead, float *target );
int GameImport_BotPredictVisiblePosition( float *origin, int areanum, void *goal, int travelflags, float *target );
int GameImport_BotAllocMoveState( void );
void GameImport_BotFreeMoveState( int handle );
void GameImport_BotInitMoveState( int handle, void *initmove );
int GameImport_BotChooseBestFightWeapon( int weaponstate, int *inventory );
void GameImport_BotGetWeaponInfo( int weaponstate, int weapon, void *weaponinfo );
int GameImport_BotLoadWeaponWeights( int weaponstate, char *filename );
int GameImport_BotAllocWeaponState( void );
void GameImport_BotFreeWeaponState( int weaponstate );
void GameImport_BotResetWeaponState( int weaponstate );
int GameImport_GeneticParentsAndChildSelection( int numranks, float *ranks, int *parent1, int *parent2, int *child );
int GameImport_PC_LoadSource( const char *filename );
int GameImport_PC_FreeSource( int handle );
int GameImport_PC_ReadToken( int handle, void *pc_token );
int GameImport_PC_SourceFileAndLine( int handle, char *filename, int *line );
void Game_Init( int levelTime, int randomSeed, int restart );
void Game_Shutdown( int restart );
int Game_WriteCheckpoint( void *writer );
int Game_ReadCheckpointCvars( const void *reader, int apply );
int Game_ReadCheckpoint( const void *reader, int apply );
void Game_LinkCheckpointEntities( void );
int Game_RestoreCheckpointRandom( const void *reader );
const char *Game_ClientConnect( int clientNum, int firstTime, int isBot );
void Game_RunFrame( int time );
int Game_ConsoleCommand( void );
int Game_BotStartFrame( int time );
void Game_ClientThink( int clientNum );
void Game_ClientUserinfoChanged( int clientNum );
void Game_ClientDisconnect( int clientNum );
void Game_ClientBegin( int clientNum );
void Game_ClientCommand( int clientNum );
#ifdef __cplusplus
}
#endif

#endif
