cmake_minimum_required(VERSION 3.25)
project(aftershock_cook LANGUAGES CXX)
add_executable(aftershock-cook-bc7 bc7.cpp ../../third_party/bc7enc/bc7enc.cpp)
target_include_directories(aftershock-cook-bc7 PRIVATE ../../third_party/bc7enc)
target_compile_features(aftershock-cook-bc7 PRIVATE cxx_std_20)
if(MSVC)
  target_compile_options(aftershock-cook-bc7 PRIVATE /fp:strict)
else()
  target_compile_options(aftershock-cook-bc7 PRIVATE -ffp-contract=off -fno-fast-math)
endif()
