#!/usr/bin/env python3
"""Generate delta field tables from q_shared.h member annotations.

@net order:bits annotates a scalar; [index]:order:bits and .member:order:bits
annotate vector/trajectory leaves. Width zero means float. Negative widths are
signed. number, array and local mark fields handled separately by the codec.
Wire order is explicit so source layout edits cannot silently reorder the stream.
"""
import argparse
import hashlib
from pathlib import Path
import re

ROOT = Path(__file__).resolve().parents[1]
HEADER = ROOT / 'engine/qcommon/q_shared.h'
OUTPUT = ROOT / 'engine/qcommon/replication.inc'
STATE_OUTPUT = ROOT / 'engine/public/state_replication.h'
MEMBER = re.compile(r'^\s*(int32_t|vec3_t|trajectory_t|trType_t) (\w+)(?:\[([\w]+)\])?;')


def constant(value, text):
    if re.fullmatch(r'-?\d+', value):
        return int(value)
    match = re.search(r'^#define\s+' + re.escape(value) + r'\s+(\d+)\b', text, re.M)
    if not match:
        raise ValueError('unknown integer constant: ' + value)
    return int(match[1])


def body(text, name):
    end = text.index('} ' + name + ';')
    start = text.rfind('typedef struct', 0, end)
    return text[text.index('{', start) + 1:end]


def members(text, name):
    return [match.groups() for line in body(text, name).splitlines()
            if (match := MEMBER.match(line))]


def leaves(kind, name, count, text):
    if kind == 'vec3_t':
        return [name + f'[{i}]' for i in range(3)]
    if kind == 'trajectory_t':
        return [leaf for k, n, c in members(text, 'trajectory_t')
                for leaf in leaves(k, name + '.' + n, c, text)]
    if count:
        return [name + f'[{i}]' for i in range(constant(count, text))]
    return [name]


def describe(text, name):
    fields, separate, offset = [], [], 0
    for line in body(text, name).splitlines():
        declaration = line.split('//', 1)[0].strip()
        if not declaration:
            continue
        match = MEMBER.match(line)
        if not match or '@net ' not in line:
            raise ValueError(name + ': every member needs a supported declaration and @net annotation: ' + line)
        kind, member, count = match.groups()
        paths = leaves(kind, member, count, text)
        tokens = line.split('@net ', 1)[1].split()
        if tokens == ['local'] or (len(tokens) == 1 and tokens[0].startswith(('number:', 'array:'))):
            tag = tokens[0]
            if tag.startswith('number:') and (name != 'entityState_t' or member != 'number' or count):
                raise ValueError('number annotation belongs only to entityState_t.number')
            if tag.startswith('array:') and (name != 'playerState_t' or member not in ('stats', 'persistant', 'ammo', 'powerups') or not count):
                raise ValueError('unsupported separately encoded array')
            separate.append((member, offset, len(paths), tag))
        else:
            found = set()
            for token in tokens:
                values = token.split(':')
                suffix, rank, width = (['', *values] if len(values) == 2 else values)
                path = member + suffix
                if path not in paths or path in found:
                    raise ValueError('unknown or repeated member leaf: ' + path)
                found.add(path)
                bits = constant(width, text)
                if not -32 <= bits <= 32:
                    raise ValueError('invalid bit width: ' + width)
                fields.append((int(rank), path, offset + paths.index(path) * 4, bits))
            if found != set(paths):
                raise ValueError('missing leaf annotations for ' + member)
        offset += len(paths) * 4
    fields.sort()
    if [field[0] for field in fields] != list(range(len(fields))):
        raise ValueError(name + ': wire order must be unique and contiguous from zero')
    if name == 'entityState_t' and separate != [('number', 0, 1, 'number:GENTITYNUM_BITS')]:
        raise ValueError('all entity fields except number must be delta encoded')
    return fields, separate, offset


def generate(text):
    output = ['// Generated by tools/replication.py from q_shared.h. Do not edit.']
    schema = []
    for kind in ('entity', 'player'):
        name = kind + 'State_t'
        fields, separate, size = describe(text, name)
        schema.append((name, fields, separate, size))
        output.append('static const netField_t ' + kind + 'StateFields[] = {')
        for _, path, _, bits in fields:
            output.append(f'\t{{ "{path}", (int)offsetof( {name}, {path} ), {bits} }},')
        output.append('};')
    digest = hashlib.sha256(repr(schema).encode('ascii')).hexdigest()
    output.append(f'static const char replicationSchema[] = "{digest}";')
    return '\n'.join(output) + '\n'


def state_members(text, name, prefix=''):
    for kind, member, count in members(text, name):
        path = prefix + member
        if kind == 'trajectory_t':
            yield from state_members(text, 'trajectory_t', path + '.')
        else:
            yield path, ('Float32' if kind == 'vec3_t' else 'UInt32' if kind == 'trType_t' else 'Int32'), (3 if kind == 'vec3_t' else constant(count, text) if count else 1)


def generate_state(text):
    output = ['// Generated by tools/replication.py from q_shared.h. Do not edit.',
              '// Include after the engine or native game shared state declarations.',
              '#ifndef STATE_REPLICATION_H', '#define STATE_REPLICATION_H',
              '#include "state_public.h"']
    for kind in ('entity', 'player'):
        name = kind + 'State_t'
        describe(text, name)  # Enforce the same exhaustive inventory as the wire tables.
        table = kind + 'SaveFields'
        output.append('inline constexpr stateField_t ' + table + '[] = {')
        for path, field_type, count in state_members(text, name):
            output.append(f'\t{{ "{path}", offsetof( {name}, {path} ), {count}, stateType_t::{field_type} }},')
        output.append('};')
        output.append(f'inline constexpr stateSchema_t {kind}StateSchema = {{ "{name}", 1, 1, sizeof( {name} ), {table}, sizeof( {table} ) / sizeof( {table}[0] ) }};')
    output.append('#endif')
    return '\n'.join(output) + '\n'


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--check', action='store_true')
    args = parser.parse_args()
    source = HEADER.read_text()
    game = (ROOT / 'game/bg/q_shared.h').read_text()
    for name in ('trajectory_t', 'entityState_t', 'playerState_t'):
        if members(source, name) != members(game, name):
            raise SystemExit('engine/game declarations differ: ' + name)
    for path, generated in ((OUTPUT, generate(source)), (STATE_OUTPUT, generate_state(source))):
        if args.check:
            if not path.exists() or path.read_text() != generated:
                raise SystemExit('stale replication description: run python3 tools/replication.py')
        else:
            path.write_text(generated)
    print('PASS: generated replication descriptions match annotated state definitions')


if __name__ == '__main__':
    main()
