# Explicit production source lists migrated from the verified Make build.

set(COMMON_SOURCES
  engine/entities/entities.cpp
  engine/weapons/weapons_assets.cpp
  engine/weapons/weapons.cpp
  engine/animation/animation.cpp
  engine/animation/animation_assets.cpp
  third_party/sha256/sha-256.c
  engine/server/sv_bot.cpp
  engine/server/sv_client.cpp
  engine/server/sv_ccmds.cpp
  engine/server/sv_filter.cpp
  engine/server/sv_game.cpp
  engine/server/sv_identity.cpp
  engine/server/sv_init.cpp
  engine/server/sv_main.cpp
  engine/server/sv_net_chan.cpp
  engine/server/sv_replication.cpp
  engine/server/sv_snapshot.cpp
  engine/server/sv_world.cpp
  engine/qcommon/cm_physics.cpp
  engine/qcommon/cm_load.cpp
  engine/qcommon/cm_patch.cpp
  engine/qcommon/cm_polylib.cpp
  engine/qcommon/cm_test.cpp
  engine/qcommon/cm_trace.cpp
  engine/qcommon/cmd.cpp
  engine/qcommon/common.cpp
  engine/platform/sys_runtime.cpp
  engine/platform/sys_services.cpp
  engine/qcommon/cvar.cpp
  engine/qcommon/files.cpp
  engine/qcommon/history.cpp
  engine/qcommon/keys.cpp
  engine/qcommon/md4.cpp
  engine/qcommon/md5.cpp
  engine/qcommon/msg.cpp
  engine/qcommon/net_chan.cpp
  engine/qcommon/net_history.cpp
  engine/platform/net_ip.cpp
  engine/qcommon/huffman.cpp
  engine/qcommon/huffman_static.cpp
  engine/qcommon/q_math.cpp
  engine/qcommon/q_shared.cpp
  third_party/minizip/unzip.cpp
  engine/botlib/be_aas_bspq3.cpp
  engine/botlib/be_aas_cluster.cpp
  engine/botlib/be_aas_debug.cpp
  engine/botlib/be_aas_entity.cpp
  engine/botlib/be_aas_file.cpp
  engine/botlib/be_aas_main.cpp
  engine/botlib/be_aas_move.cpp
  engine/botlib/be_aas_optimize.cpp
  engine/botlib/be_aas_reach.cpp
  engine/botlib/be_aas_route.cpp
  engine/botlib/be_aas_routealt.cpp
  engine/botlib/be_aas_sample.cpp
  engine/botlib/be_ai_char.cpp
  engine/botlib/be_ai_chat.cpp
  engine/botlib/be_ai_gen.cpp
  engine/botlib/be_ai_goal.cpp
  engine/botlib/be_ai_move.cpp
  engine/botlib/be_ai_weap.cpp
  engine/botlib/be_ai_weight.cpp
  engine/botlib/be_ea.cpp
  engine/botlib/be_interface.cpp
  engine/botlib/l_crc.cpp
  engine/botlib/l_libvar.cpp
  engine/botlib/l_log.cpp
  engine/botlib/l_memory.cpp
  engine/botlib/l_precomp.cpp
  engine/botlib/l_script.cpp
  engine/botlib/l_struct.cpp
)

set(CLIENT_SOURCES
  engine/ui/ui.cpp
  engine/physics/physics.cpp
  engine/client/cl_physics.cpp
  engine/client/cl_cgame.cpp
  engine/client/cl_cin.cpp
  engine/client/cl_console.cpp
  engine/client/cl_input.cpp
  engine/client/cl_voice.cpp
  engine/client/cl_keys.cpp
  engine/client/cl_main.cpp
  engine/client/cl_net_chan.cpp
  engine/client/cl_parse.cpp
  engine/client/cl_scrn.cpp
  engine/client/cl_ui.cpp
  engine/client/cl_data_ui.cpp
  engine/client/cl_avi.cpp
  engine/client/cl_jpeg.cpp
  engine/sound/snd_adpcm.cpp
  engine/sound/snd_dma.cpp
  engine/sound/snd_mem.cpp
  engine/sound/snd_mix.cpp
  engine/sound/snd_spatial.cpp
  engine/sound/snd_event.cpp
  engine/sound/snd_authored.cpp
  engine/sound/snd_voice.cpp
  engine/sound/snd_wavelet.cpp
  engine/sound/snd_main.cpp
  engine/sound/snd_codec.cpp
  engine/sound/snd_codec_wav.cpp
  third_party/zlib/puff.cpp
)

set(JPEG_SOURCES
  third_party/libjpeg/jaricom.c
  third_party/libjpeg/jcapimin.c
  third_party/libjpeg/jcapistd.c
  third_party/libjpeg/jcarith.c
  third_party/libjpeg/jccoefct.c
  third_party/libjpeg/jccolor.c
  third_party/libjpeg/jcdctmgr.c
  third_party/libjpeg/jchuff.c
  third_party/libjpeg/jcinit.c
  third_party/libjpeg/jcmainct.c
  third_party/libjpeg/jcmarker.c
  third_party/libjpeg/jcmaster.c
  third_party/libjpeg/jcomapi.c
  third_party/libjpeg/jcparam.c
  third_party/libjpeg/jcprepct.c
  third_party/libjpeg/jcsample.c
  third_party/libjpeg/jctrans.c
  third_party/libjpeg/jdapimin.c
  third_party/libjpeg/jdapistd.c
  third_party/libjpeg/jdarith.c
  third_party/libjpeg/jdatadst.c
  third_party/libjpeg/jdatasrc.c
  third_party/libjpeg/jdcoefct.c
  third_party/libjpeg/jdcolor.c
  third_party/libjpeg/jddctmgr.c
  third_party/libjpeg/jdhuff.c
  third_party/libjpeg/jdinput.c
  third_party/libjpeg/jdmainct.c
  third_party/libjpeg/jdmarker.c
  third_party/libjpeg/jdmaster.c
  third_party/libjpeg/jdmerge.c
  third_party/libjpeg/jdpostct.c
  third_party/libjpeg/jdsample.c
  third_party/libjpeg/jdtrans.c
  third_party/libjpeg/jerror.c
  third_party/libjpeg/jfdctflt.c
  third_party/libjpeg/jfdctfst.c
  third_party/libjpeg/jfdctint.c
  third_party/libjpeg/jidctflt.c
  third_party/libjpeg/jidctfst.c
  third_party/libjpeg/jidctint.c
  third_party/libjpeg/jmemmgr.c
  third_party/libjpeg/jmemnobs.c
  third_party/libjpeg/jquant1.c
  third_party/libjpeg/jquant2.c
  third_party/libjpeg/jutils.c
)

set(OGG_SOURCES
  third_party/libogg/src/bitwise.c
  third_party/libogg/src/framing.c
)

set(VORBIS_SOURCES
  third_party/libvorbis/lib/analysis.c
  third_party/libvorbis/lib/bitrate.c
  third_party/libvorbis/lib/block.c
  third_party/libvorbis/lib/codebook.c
  third_party/libvorbis/lib/envelope.c
  third_party/libvorbis/lib/floor0.c
  third_party/libvorbis/lib/floor1.c
  third_party/libvorbis/lib/info.c
  third_party/libvorbis/lib/lookup.c
  third_party/libvorbis/lib/lpc.c
  third_party/libvorbis/lib/lsp.c
  third_party/libvorbis/lib/mapping0.c
  third_party/libvorbis/lib/mdct.c
  third_party/libvorbis/lib/psy.c
  third_party/libvorbis/lib/registry.c
  third_party/libvorbis/lib/res0.c
  third_party/libvorbis/lib/smallft.c
  third_party/libvorbis/lib/sharedbook.c
  third_party/libvorbis/lib/synthesis.c
  third_party/libvorbis/lib/vorbisfile.c
  third_party/libvorbis/lib/window.c
)

set(VULKAN_SOURCES
  engine/effects/effects.cpp
  engine/render/tr_effects.cpp
  engine/render/tr_post.cpp
  engine/render/tr_stream.cpp
  engine/render/tr_temporal.cpp
  engine/render/tr_animation.cpp
  engine/render/tr_backend.cpp
  engine/render/tr_bsp.cpp
  engine/render/tr_cmds.cpp
  engine/render/tr_curve.cpp
  engine/renderercommon/tr_font.cpp
  engine/render/tr_cooked.cpp
  engine/render/tr_image.cpp
  engine/renderercommon/tr_image_png.cpp
  engine/renderercommon/tr_image_jpg.cpp
  engine/renderercommon/tr_image_bmp.cpp
  engine/renderercommon/tr_image_tga.cpp
  engine/renderercommon/tr_image_pcx.cpp
  engine/render/tr_init.cpp
  engine/render/tr_light.cpp
  engine/render/tr_main.cpp
  engine/render/tr_marks.cpp
  engine/render/tr_mesh.cpp
  engine/render/tr_model.cpp
  engine/render/tr_model_iqm.cpp
  engine/renderercommon/tr_noise.cpp
  engine/render/tr_scene.cpp
  engine/render/tr_shadow.cpp
  engine/render/tr_probes.cpp
  engine/render/tr_shade.cpp
  engine/render/tr_shade_calc.cpp
  engine/render/tr_shader.cpp
  engine/render/tr_shadows.cpp
  engine/render/tr_sky.cpp
  engine/render/tr_surface.cpp
  engine/render/tr_world.cpp
  engine/renderervk/vk.cpp
  engine/rhi/rhi_graph.cpp
  engine/render/vk_flares.cpp
  engine/render/vk_vbo.cpp
)

set(NATIVE_GAME_SOURCES
  game/game/g_rewind.cpp
  game/game/g_data_weapons.cpp
  game/game/g_animation.cpp
  game/game/ai_chat.cpp
  game/game/ai_cmd.cpp
  game/game/ai_dmnet.cpp
  game/game/ai_dmq3.cpp
  game/game/ai_main.cpp
  game/game/ai_team.cpp
  game/game/ai_vcmd.cpp
  game/bg/bg_misc.cpp
  game/bg/bg_animation.cpp
  game/bg/bg_weapons.cpp
  game/bg/bg_pmove.cpp
  game/bg/bg_slidemove.cpp
  game/game/g_active.cpp
  game/game/g_arenas.cpp
  game/game/g_bot.cpp
  game/game/g_client.cpp
  game/game/g_cmds.cpp
  game/game/g_combat.cpp
  game/game/g_items.cpp
  game/game/g_main.cpp
  game/game/g_mem.cpp
  game/game/g_misc.cpp
  game/game/g_missile.cpp
  game/game/g_mover.cpp
  game/game/g_session.cpp
  game/game/g_spawn.cpp
  game/game/g_composed.cpp
  game/game/g_svcmds.cpp
  game/game/g_native.cpp
  game/game/g_target.cpp
  game/game/g_team.cpp
  game/game/g_trigger.cpp
  game/game/g_utils.cpp
  game/game/g_weapon.cpp
  game/bg/q_math.cpp
  game/bg/q_shared.cpp
  game/bg/bg_lib.cpp
)

set(NATIVE_CGAME_SOURCES
  game/cgame/cg_data_weapons.cpp
  game/cgame/cg_physics.cpp
  game/cgame/cg_animation.cpp
  game/bg/bg_misc.cpp
  game/bg/bg_animation.cpp
  game/bg/bg_weapons.cpp
  game/bg/bg_pmove.cpp
  game/bg/bg_slidemove.cpp
  game/cgame/cg_consolecmds.cpp
  game/cgame/cg_draw.cpp
  game/cgame/cg_drawtools.cpp
  game/cgame/cg_effects.cpp
  game/cgame/cg_ents.cpp
  game/cgame/cg_event.cpp
  game/cgame/cg_info.cpp
  game/cgame/cg_localents.cpp
  game/cgame/cg_main.cpp
  game/cgame/cg_marks.cpp
  game/cgame/cg_players.cpp
  game/cgame/cg_playerstate.cpp
  game/cgame/cg_predict.cpp
  game/cgame/cg_scoreboard.cpp
  game/cgame/cg_servercmds.cpp
  game/cgame/cg_snapshot.cpp
  game/cgame/cg_native.cpp
  game/cgame/cg_view.cpp
  game/cgame/cg_weapons.cpp
  game/bg/q_math.cpp
  game/bg/q_shared.cpp
  game/bg/bg_lib.cpp
)

set(NATIVE_UI_SOURCES
  game/bg/bg_misc.cpp
  game/ui/ui_addbots.cpp
  game/ui/ui_atoms.cpp
  game/ui/ui_cdkey.cpp
  game/ui/ui_cinematics.cpp
  game/ui/ui_confirm.cpp
  game/ui/ui_connect.cpp
  game/ui/ui_controls2.cpp
  game/ui/ui_credits.cpp
  game/ui/ui_demo2.cpp
  game/ui/ui_display.cpp
  game/ui/ui_gameinfo.cpp
  game/ui/ui_ingame.cpp
  game/ui/ui_loadconfig.cpp
  game/ui/ui_main.cpp
  game/ui/ui_menu.cpp
  game/ui/ui_mfield.cpp
  game/ui/ui_mods.cpp
  game/ui/ui_network.cpp
  game/ui/ui_options.cpp
  game/ui/ui_playermodel.cpp
  game/ui/ui_players.cpp
  game/ui/ui_playersettings.cpp
  game/ui/ui_preferences.cpp
  game/ui/ui_qmenu.cpp
  game/ui/ui_removebots.cpp
  game/ui/ui_saveconfig.cpp
  game/ui/ui_serverinfo.cpp
  game/ui/ui_servers2.cpp
  game/ui/ui_setup.cpp
  game/ui/ui_sound.cpp
  game/ui/ui_sparena.cpp
  game/ui/ui_specifyserver.cpp
  game/ui/ui_splevel.cpp
  game/ui/ui_sppostgame.cpp
  game/ui/ui_spskill.cpp
  game/ui/ui_startserver.cpp
  game/ui/ui_native.cpp
  game/ui/ui_team.cpp
  game/ui/ui_teamorders.cpp
  game/ui/ui_video.cpp
  game/bg/q_math.cpp
  game/bg/q_shared.cpp
  game/bg/bg_lib.cpp
)
